config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users,only:[:show,:edit,:update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  resources :posts
  root "posts#index"
  get 'jobs' => 'posts#jobs'
  get 'columns' => 'posts#columns'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :name,presence: true
	validates :title,presence: true
	validates :content,presence: true
	mount_uploader :image, ImageUploader
	acts_as_taggable_on :places,:jobs # post.label_list が追加される
	acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
	self.per_page = 9
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :admin_user,only:[:new,:create,:edit,:upadate,:destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = if 
              params[:tag].present? 
                Post.tagged_with(params[:tag]).order(created_at: :desc)
              else
                Post.all.includes(:tags).order(created_at: :desc)
              end

    @users=User.all
  
  end

  def jobs
    @jobs= if 
           params[:tag].present? 
              Post.where(category: 'job').where(active: 'true').tagged_with(params[:tag]).page(params[:page]).order(created_at: :desc)
           else
              Post.where(category: 'job').where(active: 'true').includes(:tags).page(params[:page]).order(created_at: :desc)
           end
  end

  def columns
    @columns= if 
              params[:tag].present? 
                Post.where(category: 'column').tagged_with(params[:tag]).page(params[:page]).order(created_at: :desc)
              else
                Post.where(category: 'column').includes(:tags).page(params[:page]).order(created_at: :desc)
              end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '新規投稿を作成しました' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿を更新しました' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name,:title,:category,:content,:active,:image,:place_list,:job_list)
    end

    def admin_user
        unless current_user.role == "admin"
          redirect_to(root_path) 
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
 <%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.check_box :active,{},"true","false" %> 
    <%= f.label :active, "募集状況" %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, [["求人", "job"], ["コラム", "column"]] %>
  </div>

  <div class="field">
    <%= f.label :place_list, "場所" %><br>
    <%= text_field_tag 'post[place_list]', @post.place_list.join(',') %>
  </div>

  <div class="field">
    <%= f.label :job_list, "職種" %><br>
    <%= text_field_tag 'post[job_list]', @post.job_list.join(',') %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content %>        
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_tags.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= link_to tag, posts_path(tag: tag) %></span>
<% end %>

app/views/posts/columns.html.erb
<div class="main-wrapper">
  <div class="main">
    <div class="columns-copy">
      <h2><%= image_tag("top.png") %>募集中のシゴト</h2>
    </div>
    <% @columns.each do |column| %>
      <% if column.category=="column" %>
        <div class="column">
          <%= image_tag(column.image) %>
          <div class="title">
            <div><p><%= column.title%></p></div>
          </div>
          <div class="data">
            <p><%= image_tag("company.png") %>株式会社ジェーティービー</p>
            <p><%= image_tag("job.png") %>

            <% column.job_list.each do |tag| %>
              <span class="label label-primary"><%= link_to tag, columns_path(tag: tag) %></span>
            <% end %>
            
            </p>
            <p><%= image_tag("place.png") %>

            <% column.place_list.each do |tag| %>
              <span class="label label-primary"><%= link_to tag, columns_path(tag: tag) %></span>
            <% end %>

            </p>
            <p><%= image_tag("reword.png") %>30,000</p>
          </div>
          <div class="content">テキストテキストテキストテキストテキストテキストテキストテキ
          ストテキストテキストテキストテキスト</div>
          <% if user_signed_in? %>
            <% if current_user.role=="admin" %>
              <td><%= link_to 'Edit', edit_post_path(column) %></td>
              <td><%= link_to 'Destroy', column, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= will_paginate @columns %>



<%= stylesheet_link_tag "inside/columns" %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- メインビジュアル -->
<div class="main-visual">
  <%= image_tag("main.jpg") %>
  <div class="main-copy">
    <h1>あなたの旅をシゴトにしよう</h1>
    <h3 class="sub-copy">文章・写真・動画などのコンテンツを作りながら旅したい、<br>すごい旅人募集します</h3>
  </div>
</div>

<!-- 求人、コラム一覧 -->
<div class="main-wrapper">
  <div class="main">
    <div class="active-jobs">
      <div class="aj-copy">
        <h2><%= image_tag("top.png") %>募集中のシゴト</h2>
      </div>
      <% @posts.each do |post| %>
        <% if post.active=="true" %>
          <% if post.category=="job" %>
            <div class="active-job">
              <%= image_tag(post.image) %>
              <div class="title">
                <div><%= link_to post_path(post) do %><p><%= post.title%></p><% end %></div>
              </div>
              <div class="data">
                <p><%= image_tag("company.png") %>株式会社ジェーティービー</p>
                <p><%= image_tag("job.png") %>編集、撮影</p>
                <p><%= image_tag("place.png") %><%= render 'tags', tag_list: post.place_list %></p>
                <p><%= image_tag("reword.png") %>30,000</p>
              </div>
              <div class="content">テキストテキストテキストテキストテキストテキストテキストテキ
              ストテキストテキストテキストテキスト</div>
              <% if user_signed_in? %>
                <% if current_user.role=="admin" %>
                  <td><%= link_to 'Edit', edit_post_path(post) %></td>
                  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="side-menu">

    <div class="columns">
        <div class="column-copy">
          <h2><%= image_tag("top.png") %>コラム</h2>
        </div>
        <% @posts.each do |post| %>
          <% if post.category=="column" %>
            <div class="column">
              <%= image_tag(post.image) %>
              <div class="column-content">
                <div class="column-title"><%= post.title %></div>
                <div class="column-company">株式会社ジェーティービー</div>
              <% if user_signed_in? %>
                <% if current_user.role=="admin" %>
                  <td ><%= link_to 'Edit', edit_post_path(post) %></td>
                  <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
              <% end %>
              </div>
              
            </div>
          <% end %>
        <% end %>  
    </div>

    <div class="end-jobs">
       <div class="ej-copy">
          <h2><%= image_tag("top.png") %>成功記事</h2>
        </div>
        <% @posts.each do |post| %>
          <% if post.active=="false" %>
            <% if post.category=="job" %>
              <div class="end-job">
                <%= image_tag(post.image) %>
                <div class="column-content">
                  <div class="column-title"><%= post.title %></div>
                  <div class="column-company">株式会社ジェーティービー</div>
                  <% if user_signed_in? %>
                  <% if current_user.role=="admin" %>
                    <td ><%= link_to 'Edit', edit_post_path(post) %></td>
                    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                <% end %>
                </div>
              </div>
            <% end %>  
          <% end %>
        <% end %>  
      
    </div>
    </div>
    </div>
  </div>
</div>
<%= stylesheet_link_tag "inside/index" %>

app/views/posts/jobs.html.erb
<div class="main-wrapper">
  <div class="main">
    <div class="post-columns">
      <div class="aj-copy">
        <h2><%= image_tag("top.png") %>募集中のシゴト</h2>
      </div>
      <% @jobs.each do |job| %>
      	<% if job.active=="true" %>
	        <% if job.category=="job" %>
	          <div class="active-job">
	            <%= image_tag(job.image) %>
	            <div class="title">
	              <div><p><%= job.title%></p></div>
	            </div>
	            <div class="data">
	              <p><%= image_tag("company.png") %>株式会社ジェーティービー</p>
	              <p><%= image_tag("job.png") %>

	              <% job.job_list.each do |tag| %>
	                <span class="label label-primary"><%= link_to tag, jobs_path(tag: tag) %></span>
	              <% end %>
	              
	              </p>
	              <p><%= image_tag("place.png") %>

	              <% job.place_list.each do |tag| %>
	                <span class="label label-primary"><%= link_to tag, jobs_path(tag: tag) %></span>
	              <% end %>

	              </p>
	              <p><%= image_tag("reword.png") %>30,000</p>
	            </div>
	            <div class="content">テキストテキストテキストテキストテキストテキストテキストテキ
	            ストテキストテキストテキストテキスト</div>
	            <% if user_signed_in? %>
	              <% if current_user.role=="admin" %>
	                <td><%= link_to 'Edit', edit_post_path(job) %></td>
	                <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	              <% end %>
	            <% end %>
	          </div>
	        <% end %>
	    <% end %>
      <% end %>
    </div>
<%= will_paginate @jobs %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if @post.category=="job" %>
	<strong>募集状況:</strong>
		<% if @post.active=="true" %>
			<p>募集中</p>
		<% else %>
			<p>募集終了</p>
		<% end %>	

	<p>
		<strong>タイトル:</strong>
		<%= @post.title %>
	</p>

		<strong>コンテンツ:</strong>
		<%== @post.content %>

	<p>
		<strong>この記事のライター:</strong>
		<%= @post.name %>
	</p>
	<%= link_to '問い合わせ', inquiry_path %>
<% else %>
	<p>
		<strong>タイトル:</strong>
		<%= @post.title %>
	</p>

		<strong>コンテンツ:</strong>
		<%== @post.content %>

	<p>
		<strong>この記事のライター:</strong>
		<%= @post.name %>
	</p>
<% end %>
<% if user_signed_in? %>
	<% if current_user.role=="admin" %>
		<br>
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Back', posts_path %>
		</br>
	<% end %>
<% end %>