config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users,only:[:show,:edit,:update]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  resources :posts
  root "posts#index"
  get 'jobs' => 'posts#jobs'
  get 'columns' => 'posts#columns'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Sagojo</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="header-wrapper">
			<header>
				<div class="header-inner">
					<div class="logo">
						<%= link_to root_path do %>
							<%= image_tag 'logo.png' %>
						<% end %>
					</div>
					<div class="g-menu">
						<div class="menu-left">	
							<ul>
								<li><%= link_to "シゴト一覧",jobs_path %></li>
								<li><%= link_to "コラム一覧",columns_path %></li>
								<li><%= link_to "アバウト",static_pages_about_path %></li>
								<li><%= link_to "ヘルプ",static_pages_help_path  %></li>
							</ul>
						</div>
						<div class="menu-right">
							<ul>
								<% if !user_signed_in? %>
									<li><%= link_to "サインアップ", new_user_registration_path  %></li>
									<li><%= link_to "サインイン",  new_user_session_path  %></li>
								<% else %>
									<li><%= link_to "マイページ",  current_user %></li>
									<li><%= link_to "サインアウト", destroy_user_session_path,:method => :delete  %></li>
								<% if current_user.role == "admin" %>
									<li><%= link_to "新規投稿",  new_post_path  %></li>
									<li><%= link_to "管理画面",  "http://localhost:3000/admin/"  %></li>
								<% end %>
								<% end %>
							</ul>
						</div>
					</div>
				</div>
			</header>
		</div>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	<%= yield %>
	
	<footer>
		<div class="footer-inner">
			<div class="footer-logo">
			<p><%= image_tag 'logo.png' %></p>
			</div>
			<div class="footer-left">
				<p>about sagojo</p>
				<p>企業の方へ</p>
				<p>個人情報について</p>
				<p>サイトポリシー</p>
			</div>
			<div class="footer-right">
				<p>FAQ</p>
				<p>クッキーポリシー</p>
				<p>ヘルプ</p>
				<p>お問い合わせ</p>
			</div>
			<p class="copy-right">Copyright © SAGOJO All Rights Reserved.</p>
		</div>
	</footer>
	</body>
</html>